export default function TermsAndConditions() {
  return (
    <section id="terms" className="px-4 py-6 lg:py-12">
      <div className="max-w-7xl mx-auto flex flex-col">
        <p className="text-[24px] lg:text-[48px] font-bold glow-text text-center text-[#E60023]">Terms & Conditions</p>
        <ol className="list-decimal list-inside space-y-6">
          <li>
            <span>Acceptance of Terms</span>
            <p>
              These Terms & Conditions ("Terms") form a binding agreement
              between you and Top10CasinoUK Casino Limited ("Company", "we",
              "our", "us") for use of our website and services.
            </p>
            <p>
              By visiting or using our services, you confirm that you have read,
              understood, and agreed to these Terms. If you do not agree, you
              must not access or use our services.
            </p>
          </li>

          <li>
            <span>Eligibility</span>
            <p>To use our services, you must meet the following requirements:</p>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <li>Be 18 years of age or older</li>
              <li>Reside in the United Kingdom</li>
              <li>Be legally capable of entering into contracts</li>
              <li>Not be enrolled in any self-exclusion program</li>
              <li>Not be legally restricted from gambling</li>
              <li>Provide accurate and truthful information upon registration</li>
            </ul>
            We may verify your eligibility at any time. Failure to comply may
            result in suspension or closure of your account.
          </li>

          <li>
            <span>Account Registration</span>
            <p>Registration Requirements:</p>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <li>Only one account per person is allowed</li>
              <li>All details provided must be current and accurate</li>
              <li>Identity verification is required for withdrawals</li>
              <li>You are responsible for keeping your account secure</li>
            </ul>
            <p>Account Security:</p>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <li>Do not share your login credentials</li>
              <li>Notify us immediately of unauthorized activity</li>
              <li>Use strong, unique passwords and enable 2FA</li>
              <li>Always log out when using shared devices</li>
            </ul>
          </li>

          <li>
            <span>Deposits & Withdrawals</span>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <span>Deposits:</span>
              <li>Minimum and maximum deposit limits apply</li>
              <li>Most deposits are processed instantly</li>
              <li>Only payment methods in your own name may be used</li>
              <li>We may refuse deposits from certain sources</li>

              <span>Withdrawals:</span>
              <li>Identity verification required before first withdrawal</li>
              <li>Withdrawals usually processed within 24–48 hours</li>
              <li>Minimum withdrawal limits apply</li>
              <li>
                Funds must be returned via the same payment method used for
                deposits
              </li>
            </ul>
          </li>

          <li>
            <span>Game Rules</span>
            <p>General Rules:</p>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <li>Each game is subject to its own rules and paytables</li>
              <li>All results are generated by certified RNG systems</li>
              <li>Bets cannot be cancelled once placed</li>
              <li>Malfunctions void any affected bets or payouts</li>
              <li>We reserve the right to set betting limits</li>
            </ul>
            <p>Prohibited Conduct:</p>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <li>Exploiting bonuses or loopholes with betting systems</li>
              <li>Collusion with other players</li>
              <li>Use of bots or automated play software</li>
              <li>Attempts to manipulate outcomes</li>
              <li>Illegal activities such as money laundering</li>
            </ul>
          </li>

          <li>
            <span>Bonuses & Promotions</span>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <li>All offers are subject to their own bonus terms</li>
              <li>Wagering requirements must be met before cashout</li>
              <li>Bonuses may carry time and game restrictions</li>
              <li>We may modify or cancel promotions at any time</li>
              <li>Bonus misuse may result in removal and account closure</li>
              <li>Only one bonus per player, household, or IP</li>
            </ul>
          </li>

          <li>
            <span>Responsible Gaming</span>
            <p>We promote safe and responsible gambling:</p>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <li>Set limits on deposits, losses, or playtime</li>
              <li>Use time-outs or self-exclusion tools</li>
              <li>Access reminders such as session timers</li>
              <li>Seek support from GamCare or BeGambleAware</li>
              <li>Contact support for further assistance</li>
            </ul>
            <p>If gambling stops being enjoyable, please stop playing.</p>
            <p>
              For free help and advice, visit{" "}
              <a
                href="https://www.begambleaware.org/"
                className="underline"
              >
                BeGambleAware.org
              </a>
            </p>
          </li>

          <li>
            <span>Privacy & Data Protection</span>
            <p>
              Your data is protected by our Privacy Policy, which explains how
              we collect, store, and use your information. By using our
              services, you agree to this processing in line with UK Gambling
              Commission requirements.
            </p>
          </li>

          <li>
            <span>Limitation of Liability</span>
            <p>To the maximum extent permitted by law:</p>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <li>We provide services “as is” without warranties</li>
              <li>Our liability is limited to funds in your account</li>
              <li>We are not liable for indirect or consequential losses</li>
              <li>Service interruptions or errors do not create liability</li>
              <li>You use our site at your own risk</li>
            </ul>
          </li>

          <li>
            <span>Account Closure</span>
            <p>We may suspend or close your account if:</p>
            <ul className="list-disc list-inside ml-5 mt-2 space-y-1">
              <li>You breach these Terms or our policies</li>
              <li>We suspect fraud, abuse, or unlawful behaviour</li>
              <li>We are required to by law or regulators</li>
              <li>Operational reasons make closure necessary</li>
            </ul>
            <p>
              Upon closure, remaining balances will be refunded after necessary
              checks in line with legal obligations.
            </p>
          </li>

          <li>
            <span>Governing Law</span>
            <p>
              These Terms are governed by the laws of England and Wales. Any
              disputes will be settled exclusively in the courts of England and
              Wales.
            </p>
          </li>

          <li>
            <span>Changes to Terms</span>
            <p>
              We may amend these Terms from time to time. Updates will take
              effect when published on our site. Continued use means you accept
              the changes.
            </p>
            <p>
              Where appropriate, we will notify you of significant changes via
              email or site notice.
            </p>
          </li>
        </ol>
      </div>


      <div className="max-w-7xl mx-auto lg:text-center mt-5 lg:mt-10">
        <h2 className="text-[24px] lg:text-[48px] font-bold glow-text text-center text-[#E60023]">Discover <span className="glow-text">Premium</span>  Casinos</h2>
        <p className="text-[#000] opacity-40 text-[16px] lg:text-[20px] text-center">Expert reviews, exclusive bonuses, and trusted recommendations for the <span className="glow-text">UK's top-rated</span> online casinos</p>
        <div className="lg:w-[60%] mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 lg:gap-8 pt-5 lg:pt-10 justify-items-center">
            <div className="flex flex-col rouneded-[8px] gap-2 w-full items-center cursor-pointer group bg-white/5 backdrop-blur-sm border border-[#E60023] rounded-2xl p-4 text-center transition-all duration-300 hover:scale-105">
              <h3 className="font-bold text-[#E60023] lg:text-[20px]">50M+</h3>
              <p className="text-[14px]">Total Winnings Paid</p>
            </div>
            <div className="flex flex-col rouneded-[8px] gap-2 w-full items-center cursor-pointer group bg-white/5 backdrop-blur-sm border border-[#E60023] rounded-2xl p-4 text-center transition-all duration-300 hover:scale-105">
              <h3 className="font-bold text-[#E60023] lg:text-[20px]">500K+</h3>
              <p className="text-[14px]">Happy Players</p>
            </div>
            <div className="flex flex-col rouneded-[8px] gap-2 w-full items-center cursor-pointer group bg-white/5 backdrop-blur-sm border border-[#E60023] rounded-2xl p-4 text-center transition-all duration-300 hover:scale-105">
              <h3 className="font-bold text-[#E60023] lg:text-[20px]">5000+</h3>
              <p className="text-[14px]">Casino Games</p>
            </div>
            <div className="flex flex-col rouneded-[8px] gap-2 w-full items-center cursor-pointer group bg-white/5 backdrop-blur-sm border border-[#E60023] rounded-2xl p-4 text-center transition-all duration-300 hover:scale-105">
              <h3 className="font-bold text-[#E60023] lg:text-[20px]">24/7</h3>
              <p className="text-[14px]">Expert Support</p>
            </div>

          </div>
        </div>
      </div>

    </section>
  );
}
